/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import utils.Auth;
import utils.MsgBox;
import entity.TaiKhoan;
import utils.XImage;

/**
 *
 * @author Asus
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        setIconImage(XImage.getAppIcon());
        init();
        lblTenDN.setText(Auth.user.getTentaiKhoan());
        lblChucVu.setText(Auth.user.getChucVu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTenDN = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnDichVu = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnDatPhong = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMK = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        mniDatPhong = new javax.swing.JMenuItem();
        mniPhong = new javax.swing.JMenuItem();
        mniThanhToan = new javax.swing.JMenuItem();
        mniDichVu = new javax.swing.JMenuItem();
        mniTaiKhoan = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniDoanhThu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHÁCH SẠN");

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khachsan.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Khách sạn GFT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user1.png"))); // NOI18N

        lblTenDN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTenDN.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDN.setText("ThanhNT");

        lblChucVu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setText("Trưởng Phòng");

        btnDangXuat.setBackground(new java.awt.Color(102, 0, 102));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangxuat.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblTenDN))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTenDN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChucVu)))
                .addGap(18, 18, 18)
                .addComponent(btnDangXuat)
                .addGap(61, 61, 61))
        );

        btnNhanVien.setBackground(new java.awt.Color(255, 153, 0));
        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(102, 0, 102));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/NhanVien.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));

        btnDichVu.setBackground(new java.awt.Color(153, 153, 0));
        btnDichVu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDichVu.setForeground(new java.awt.Color(102, 0, 102));
        btnDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dichvu.png"))); // NOI18N
        btnDichVu.setText("Dịch vụ");
        btnDichVu.setFocusable(false);
        btnDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDichVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(255, 102, 102));
        btnKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(102, 0, 102));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer.png"))); // NOI18N
        btnKhachHang.setText("Khách hàng ");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnDatPhong.setBackground(new java.awt.Color(255, 51, 255));
        btnDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDatPhong.setForeground(new java.awt.Color(102, 0, 102));
        btnDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/datphong.PNG"))); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.setFocusable(false);
        btnDatPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDatPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(102, 255, 153));
        btnThanhToan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(102, 0, 102));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thanhtoan.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setFocusable(false);
        btnThanhToan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThanhToan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnPhong.setBackground(new java.awt.Color(0, 153, 153));
        btnPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(102, 0, 102));
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phong.png"))); // NOI18N
        btnPhong.setText("Phòng");
        btnPhong.setFocusable(false);
        btnPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(255, 51, 51));
        btnThongKe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(102, 0, 102));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thongke.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnHuongDan.setBackground(new java.awt.Color(204, 204, 255));
        btnHuongDan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHuongDan.setForeground(new java.awt.Color(102, 0, 102));
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huongdan.png"))); // NOI18N
        btnHuongDan.setText("Đăng ký dv");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ : 45 Phan Chu Trinh, Phường Bến Thành, Quận 1, TP Hồ Chí Minh ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/diachi.png"))); // NOI18N

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNhanVien)
                                    .addComponent(btnKhachHang))
                                .addGap(105, 105, 105)
                                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDatPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHuongDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuongDan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)))
                .addGap(14, 14, 14))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 0));

        mnuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/HeThong.png"))); // NOI18N
        mnuHeThong.setText("Hệ thống ");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/key.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DangNhap.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniDoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DoiMK.png"))); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMK);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/QuanLy.png"))); // NOI18N
        mnuQuanLy.setText("Quản Lý");

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Staff.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mnuQuanLy.add(mniNhanVien);

        mniKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Khachhang.png"))); // NOI18N
        mniKhachHang.setText("Khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhachHang);

        mniDatPhong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DatPhong1.png"))); // NOI18N
        mniDatPhong.setText("Đặt phòng");
        mniDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniDatPhong);

        mniPhong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/room.png"))); // NOI18N
        mniPhong.setText("Phòng");
        mniPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniPhong);

        mniThanhToan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        mniThanhToan.setText("Thanh toán");
        mniThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThanhToanActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniThanhToan);

        mniDichVu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/service.png"))); // NOI18N
        mniDichVu.setText("Dịch vụ");
        mniDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDichVuActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniDichVu);

        mniTaiKhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Staff.png"))); // NOI18N
        mniTaiKhoan.setText("Tài khoản");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniTaiKhoan);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thongke1.png"))); // NOI18N
        mnuThongKe.setText("Thống kê");

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DoanhThu.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThu);

        jMenuBar1.add(mnuThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        this.openDichVu();
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        this.openKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        this.openDatPhong();
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        this.openThanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        this.openPhong();
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        this.openThongKe();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        this.openDangKyDV();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        this.openKhachHang();
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mniPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhongActionPerformed
        this.openPhong();
    }//GEN-LAST:event_mniPhongActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        this.openDangNhap();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        this.DoiMatKhau();
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
        this.openTaiKhoan();
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    private void mniDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongActionPerformed
        this.openDatPhong();
    }//GEN-LAST:event_mniDatPhongActionPerformed

    private void mniThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThanhToanActionPerformed
        this.openThanhToan();
    }//GEN-LAST:event_mniThanhToanActionPerformed

    private void mniDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDichVuActionPerformed
        this.openDichVu();
    }//GEN-LAST:event_mniDichVuActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        this.openThongKe();
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.DangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.DangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDatPhong;
    private javax.swing.JMenuItem mniDichVu;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniPhong;
    private javax.swing.JMenuItem mniTaiKhoan;
    private javax.swing.JMenuItem mniThanhToan;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    // End of variables declaration//GEN-END:variables

    public void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        new ManHinhChao(this, true).setVisible(true);
        new DangNhap(this, true).setVisible(true);
    }

    public void openNhanVien() {

        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Nhân sự")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN NHÂN SỰ");
        } else {
            new QuanLyNhanVien(this, true).setVisible(true);
        }
    }

    public void openDangKyDV() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Lễ tân")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN LỄ TÂN");
        } else {
            new DangKyDichVu(this, true).setVisible(true);
        }
    }

    public void openDichVu() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Kinh doanh")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN KINH DOANH");
        } else {
            new QuanLyDichVu(this, true).setVisible(true);
        }
    }

    public void openKhachHang() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Kinh doanh")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN KINH DOANH");
        } else {
            new QuanLyKhachHang(this, true).setVisible(true);
        }

    }

    public void openPhong() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Kinh doanh")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN KINH DOANH");
        } else {
            new QuanLyPhong(this, true).setVisible(true);
        }
    }

    public void openThanhToan() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (Auth.isRole().equalsIgnoreCase("Lễ tân")) {
            new QuanLyThanhToan(this, true).setVisible(true);
        } else if (Auth.isRole().equalsIgnoreCase("Kế toán")) {
            QuanLyThanhToan tt = new QuanLyThanhToan(this, false);
            tt.Deletetab("Kế toán");
            tt.setVisible(true);

        } else {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN LỄ TÂN");
        }
    }

    public void openTaiKhoan() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Nhân sự")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN NHÂN SƯ");
        } else {
            new QuanLyTaiKhoan(this, true).setVisible(true);
        }
    }

    public void openThongKe() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Kế toán")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN KẾ TOÁN");
        } else {
            new ThongKe(this, true).setVisible(true);
        }

    }

    public void openDatPhong() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (!Auth.isRole().equalsIgnoreCase("Lễ tân")) {
            MsgBox.alert(this, "Chức năng này thuộc quyền quản lý của BỘ PHẬN LỄ TÂN");
        } else {
            new QuanLyDatPhong(this, true).setVisible(true);
        }
    }

    public void openDangNhap() {
        if (Auth.isLogin()) {
            new DangNhap(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void DangXuat() {

        Auth.clear();
        new DangNhap(this, true).setVisible(true);
        lblTenDN.setText(Auth.user.getTentaiKhoan());
        lblChucVu.setText(Auth.user.getChucVu());

    }

    public void DoiMatKhau() {
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        } else if (Auth.isRole().equalsIgnoreCase("Lễ tân")) {
            MsgBox.alert(this, "LỄ TÂN KHÔNG ĐƯỢC QUYỀN ĐỔI MẬT KHẨU");
        } else {
            new DoiMK(this, true).setVisible(true);
        }
    }
}
